node:
  server01:
    ports:
      eth0:
        dhcp:
      eth1:
        ip: 192.168.10.101/24
        gw: 192.168.10.1
  server02:
    ports:
      eth0:
        dhcp:
      eth1:
        ip: 192.168.20.200/24
        gw: 192.168.20.1
