node:
  switch01:
    mlag:
      address:
      backup-ip:
      members:
      peer-ip:
      sysmac:
      interfaces:
        bond01:
          clagid:
          members:
          mode:
          vlans:
    overlay:
      anycast-ip:
      vxlan:
        vni:
          vlan:
    ports:
      - swp1
      - swp2
    lacp:
      interfaces:
        members:
    switching:
      interface:
        mode:
        vlans:
    routing:
      lo: 10.1.1.1/32
      ospf:
        area:
        neighbors:
      bgp:
        asn: 65111
        underlay:
          external:
            peers:
              - swp1
              - swp2
          internal:
            peers:
      svi:
        vlansvi:
          ip:
          vlan:
          vrrp:
            mac:
            ip:
  switch02:
    mlag:
      address:
      backup-ip:
      members:
      peer-ip:
      sysmac:
      interfaces:
        bond01:
          clagid:
          members:
          mode:
          vlans:
    overlay:
      anycast-ip:
      vxlan:
        vni:
          vlan:
    ports:
      - swp1
      - swp2
    lacp:
      interfaces:
        members:
    switching:
      interface:
        mode:
        vlans:
    routing:
      lo: 10.2.2.2/32
      ospf:
        area:
        neighbors:
      bgp:
        asn: 65222
        underlay:
          external:
            peers:
              - swp1
              - swp2
          internal:
            peers:
      svi:
        vlansvi:
          ip:
          vlan:
          vrrp:
            mac:
            ip:
