---

- name: Enable VLAN upon reboot
  shell: echo 8021q | sudo tee -a /etc/modules

- name: Copy server02 VLAN-enabled interfaces file
  copy:
    src: interfaces-vlan
    dest: /etc/network/interfaces
    backup: yes
  when: inventory_hostname == "server02"

- name: Copy interfaces configuration
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    backup: yes
  when: inventory_hostname != "server02"

- name: Sleep for server to disconnect
  pause:
    seconds: 5

## - name: Bring up eth1
##  shell: ifdown eth1 && ifup eth1

- name: reboot
  command: /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true

- name: Sleep for server to disconnect
  pause:
    seconds: 10

- name: Wait for hosts to be up
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    state: started
    delay: 30
    timeout: 300
  ignore_errors: true
